import ExcelJS from 'exceljs';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { getDatabase } from '../db/db';
import { getAddisAbabaTimestamp } from '../utils/id-generator';

export interface ReportMetadata {
  reportTitle: string;
  generatedBy: string;
  branchName?: string;
  startDate?: string;
  endDate?: string;
}

export class ReportService {
  /**
   * Generates formatted Excel workbook buffer for any dataset
   */
  static async generateExcelReport(
    metadata: ReportMetadata,
    columns: { header: string; key: string; width?: number; isCurrency?: boolean; isNumber?: boolean }[],
    rows: Record<string, any>[]
  ): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'KIMIYA TELECOM Enterprise System';
    workbook.created = new Date();

    const worksheet = workbook.addWorksheet(metadata.reportTitle.substring(0, 30));

    // Header Styling
    worksheet.mergeCells('A1:G1');
    const titleCell = worksheet.getCell('A1');
    titleCell.value = 'KIMIYA TELECOM';
    titleCell.font = { name: 'Arial', size: 16, bold: true, color: { argb: 'FFFFFFFF' } };
    titleCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF1367F6' },
    };
    titleCell.alignment = { vertical: 'middle', horizontal: 'center' };
    worksheet.getRow(1).height = 30;

    worksheet.mergeCells('A2:G2');
    const subtitleCell = worksheet.getCell('A2');
    subtitleCell.value = `${metadata.reportTitle.toUpperCase()} - ${metadata.branchName || 'ALL BRANCHES'}`;
    subtitleCell.font = { name: 'Arial', size: 12, bold: true, color: { argb: 'FF1E293B' } };
    subtitleCell.alignment = { vertical: 'middle', horizontal: 'center' };
    worksheet.getRow(2).height = 22;

    // Metadata Row
    worksheet.mergeCells('A3:G3');
    const metaCell = worksheet.getCell('A3');
    const dateRangeStr =
      metadata.startDate && metadata.endDate
        ? `Date Range: ${metadata.startDate} to ${metadata.endDate}`
        : `Date: ${getAddisAbabaTimestamp().substring(0, 10)}`;
    metaCell.value = `Generated By: ${metadata.generatedBy} | ${dateRangeStr} | Generated At: ${getAddisAbabaTimestamp()}`;
    metaCell.font = { name: 'Arial', size: 9, italic: true, color: { argb: 'FF64748B' } };
    metaCell.alignment = { vertical: 'middle', horizontal: 'center' };
    worksheet.getRow(3).height = 18;

    worksheet.addRow([]); // Blank row at index 4

    // Table Column Headers
    const headerRow = worksheet.addRow(columns.map((c) => c.header));
    headerRow.height = 24;
    headerRow.eachCell((cell) => {
      cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFFFF' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FF0F172A' },
      };
      cell.alignment = { vertical: 'middle', horizontal: 'center' };
      cell.border = {
        top: { style: 'thin', color: { argb: 'FFCBD5E1' } },
        bottom: { style: 'medium', color: { argb: 'FFCBD5E1' } },
      };
    });

    // Populate Data Rows
    for (const item of rows) {
      const rowValues = columns.map((col) => item[col.key] ?? '-');
      const dataRow = worksheet.addRow(rowValues);
      dataRow.height = 20;

      dataRow.eachCell((cell, colIndex) => {
        const colDef = columns[colIndex - 1];
        cell.font = { name: 'Arial', size: 9 };
        cell.border = {
          bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
          left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
          right: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        };

        if (colDef.isCurrency) {
          cell.numFmt = '#,##0.00 "ETB"';
          cell.alignment = { horizontal: 'right', vertical: 'middle' };
        } else if (colDef.isNumber) {
          cell.numFmt = '#,##0';
          cell.alignment = { horizontal: 'right', vertical: 'middle' };
        } else {
          cell.alignment = { horizontal: 'left', vertical: 'middle' };
        }
      });
    }

    // Auto-fit Column Widths
    worksheet.columns = columns.map((c) => ({
      width: c.width || Math.max(c.header.length + 6, 15),
    }));

    const uint8Array = await workbook.xlsx.writeBuffer();
    return Buffer.from(uint8Array);
  }

  /**
   * Generates formatted PDF report buffer for any dataset
   */
  static generatePdfReport(
    metadata: ReportMetadata,
    columns: { header: string; dataKey: string }[],
    rows: Record<string, any>[]
  ): Buffer {
    const doc = new jsPDF({
      orientation: columns.length > 6 ? 'landscape' : 'portrait',
      unit: 'pt',
      format: 'a4',
    });

    // Brand Header
    doc.setFillColor(19, 103, 246); // Telecom Blue
    doc.rect(0, 0, doc.internal.pageSize.width, 50, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('KIMIYA TELECOM', 40, 32);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Enterprise Telecom Distribution & Finance', doc.internal.pageSize.width - 40, 32, {
      align: 'right',
    });

    // Report Title & Meta
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(metadata.reportTitle, 40, 75);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);

    const branchText = `Branch: ${metadata.branchName || 'All Branches'}`;
    const dateRangeText =
      metadata.startDate && metadata.endDate
        ? `Date Range: ${metadata.startDate} to ${metadata.endDate}`
        : `Date: ${getAddisAbabaTimestamp().substring(0, 10)}`;
    const metaText = `${branchText}  |  ${dateRangeText}  |  Generated By: ${metadata.generatedBy} (${getAddisAbabaTimestamp()})`;

    doc.text(metaText, 40, 92);

    // Render Table using autoTable
    autoTable(doc, {
      startY: 105,
      head: [columns.map((c) => c.header)],
      body: rows.map((row) => columns.map((col) => row[col.dataKey] ?? '-')),
      theme: 'striped',
      headStyles: {
        fillColor: [15, 23, 42],
        textColor: [255, 255, 255],
        fontSize: 9,
        fontStyle: 'bold',
        halign: 'center',
      },
      bodyStyles: {
        fontSize: 8,
        textColor: [30, 41, 59],
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      margin: { left: 40, right: 40 },
      didDrawPage: (data) => {
        // Footer on each page
        const pageCount = (doc.internal as any).getNumberOfPages();
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text(
          `Page ${data.pageNumber} of ${pageCount} - KIMIYA TELECOM Confidential Business Document`,
          doc.internal.pageSize.width / 2,
          doc.internal.pageSize.height - 20,
          { align: 'center' }
        );
      },
    });

    const pdfOutput = doc.output('arraybuffer');
    return Buffer.from(pdfOutput);
  }
}
